# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

align_spectras <- function(q_spectra, l_spectras, min_deviation_mz = 0.05, min_deviation_abd = 25.0) {
    .Call('_workflow_lipido_align_spectras', PACKAGE = 'workflow.lipido', q_spectra, l_spectras, min_deviation_mz, min_deviation_abd)
}

